<a href="https://colab.research.google.com/github/ambikauttamgaikwad/class_notes/blob/main/numpyactivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(10, 50)
print("original array:\n",arr1)
matrix1 = arr1.reshape(4, 10)
print("\nReshaped 4x10 matrix:\n",matrix1)
last_column = matrix1[:, -1]
print("\nLast column:\n",last_column)

original array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reshaped 4x10 matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last column:
 [19 29 39 49]


In [ ]:
mat_fives = np.full((3, 3), 5)
mat_1to9 = np.arange(1, 10).reshape(3, 3)
print("Matrix of 5s:\n", mat_fives)
print("\nMatrix 1 to 9:\n", mat_1to9)

added_mat = mat_fives + mat_1to9
print("\nAdded Matrix:\n", added_mat)

multiplied_mat = mat_fives * mat_1to9
print("\nElement-wise Multiplied Matrix:\n", multiplied_mat)

transpose_mat = multiplied_mat.T

Matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Added Matrix:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplied Matrix:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
arr3 = np.random.randint(10, 100, size=15)
print("Original Random Array:\n", arr3)

replaced_count = np.sum(arr3 > 50)

arr3[arr3 > 50] = -1

print("\nModified Array:\n", arr3)
print("\nNumber of values replaced:", replaced_count)

Original Random Array:
 [64 72 53 81 89 35 37 28 48 61 96 22 98 37 24]

Modified Array:
 [-1 -1 -1 -1 -1 35 37 28 48 -1 -1 22 -1 37 24]

Number of values replaced: 8


In [ ]:
matrix4 = np.random.rand(5, 4)
print("Original 5x4 Matrix:\n", matrix4)

row_sums = matrix4.sum(axis=1)
max_sum_row_index = np.argmax(row_sums)
print("\nSums of each row:", row_sums)
print("Row index with maximum sum:", max_sum_row_index)

row_min = matrix4.min(axis=1, keepdims=True)
row_max = matrix4.max(axis=1, keepdims=True)

normalized_matrix = (matrix4 - row_min) / (row_max - row_min)
print("\nNormalized Matrix:\n", normalized_matrix)

Original 5x4 Matrix:
 [[0.50897715 0.82088438 0.96085585 0.01539944]
 [0.14046448 0.52518612 0.34524409 0.50533633]
 [0.92296434 0.88472241 0.58730077 0.657235  ]
 [0.41760434 0.65297628 0.06698988 0.63431351]
 [0.36879689 0.67722709 0.14992739 0.62588651]]

Sums of each row: [2.30611682 1.51623103 3.05222252 1.77188401 1.82183788]
Row index with maximum sum: 2

Normalized Matrix:
 [[0.52205232 0.85195355 1.         0.        ]
 [0.         1.         0.53227992 0.94840479]
 [1.         0.88607065 0.         0.20834619]
 [0.59833207 1.         0.         0.96815154]
 [0.41507609 1.         0.         0.9026349 ]]


In [ ]:
arr5 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
print("Original Array:", arr5)

unique_elements = np.unique(arr5)
print("Unique Elements:", unique_elements)

elements, counts = np.unique(arr5, return_counts=True)
duplicates = elements[counts > 1]
print("Duplicate Elements:", duplicates)

Original Array: [1 3 5 3 7 9 1 5 5]
Unique Elements: [1 3 5 7 9]
Duplicate Elements: [1 3 5]


In [ ]:
matrix6 = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:\n", matrix6)

submatrix = matrix6[1:5, 1:5]
print("\nMiddle 4x4 Submatrix:\n", submatrix)

even_numbers = submatrix[submatrix % 2 == 0]
print("\nEven Numbers from Submatrix:\n", even_numbers)

Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even Numbers from Submatrix:
 [ 8 10 14 16 20 22 26 28]


In [ ]:
arr7 = np.arange(12).reshape(3, 4)
print("Original Matrix (3x4):\n", arr7)

reshaped_2x6 = arr7.reshape(2, 6)
print("\nReshaped Matrix (2x6):\n", reshaped_2x6)

flattened_arr = reshaped_2x6.flatten()
print("\nFlattened 1D Array:\n", flattened_arr)

final_matrix = flattened_arr.reshape(4, 3)
print("\nFinal Reshaped Matrix (4x3):\n", final_matrix)

Original Matrix (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped Matrix (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Final Reshaped Matrix (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
print("Initial Matrix:\n", a)

a_with_row = np.append(a, [[5, 6]], axis=0)
print("\nAfter Appending New Row:\n", a_with_row)

new_column = np.array([[7], [8], [9]])
final_a = np.append(a_with_row, new_column, axis=1)
print("\nAfter Appending New Column:\n", final_a)

Initial Matrix:
 [[1 2]
 [3 4]]

After Appending New Row:
 [[1 2]
 [3 4]
 [5 6]]

After Appending New Column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined_arr = np.concatenate((a, b, c))
print("Joined 1D Array:\n", joined_arr)

matrix9 = joined_arr.reshape(3, 3)
print("\nReshaped 3x3 Matrix:\n", matrix9)

diagonal_elements = np.diag(matrix9)
print("\nDiagonal Elements:\n", diagonal_elements)

Joined 1D Array:
 [1 2 3 4 5 6 7 8 9]

Reshaped 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Elements:
 [1 5 9]


In [ ]:
arr10 = np.arange(1, 21)
print("Original Array:\n", arr10)

filtered_values = arr10[(arr10 % 3 == 0) | (arr10 % 5 == 0)]
print("\nValues divisible by 3 or 5:\n", filtered_values)

count_values = len(filtered_values)
print("\nTotal count of these values:", count_values)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]

Total count of these values: 9
